services:
  rasa:
    build: ./chatbot  # Build from your chatbot directory
    ports:
      - "5005:5005"
    volumes:
      - ./chatbot/models:/app/models:rw
    command: "run --enable-api --cors '*' --debug"
    depends_on:
      - action_server

  action_server:
    build: ./chatbot  # Same build context as rasa service
    ports:
      - "5055:5055"
    command: "run actions --cors '*'"
    env_file:
      - ./chatbot/database.env

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro